version: "3"
services:
  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    restart: always
    env_file: .env
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    ports:
      - 1883:1883
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_NODENAME: "rabbitmq@localhost"
      VIRTUAL_HOST: "rabbitmq.${HOSTNAME:-localhost}"
      VIRTUAL_PORT: "15672"

  caddy:
    build: ./caddy
    container_name: caddy
    restart: always
    env_file: .env
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy:/etc/caddycerts
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - 80:80
      - 443:443

networks:
  default:
    external:
      name: miot

volumes:
  rabbitmq: {}
  caddy: {}
