version: "3"
services:
  led_clock_backend:
    build: .
    container_name: led_clock_backend
    restart: always
    env_file: .env
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      VIRTUAL_HOST: "${HOSTNAME:-localhost}"
      VIRTUAL_PORT: "3000"
      MQTT_ENDPOINT: "${MQTT_ENDPOINT:-tcp://rabbitmq:1883}"

networks:
  default:
    external:
      name: miot
